# DESAFIO
* Cargar el archivo estudiantes_notas en su entorno de trabajo.
* Cambiar dimensiones: Experimentar con diferentes formas del arreglo.
* Normalización: Comparar métodos de normalización (Min-Max y Z-Score).
* Operaciones estadísticas: Calcular desviación estándar, promedios, etc.
* Filtro de datos: Filtrar estudiantes que cumplan ciertos criterios, como obtener más de 70 en Matemáticas.

## Cargar el archivo estudiantes_notas en su entorno de trabajo.

In [3]:
import numpy as np

# Cargar los datos desde el archivo CSV 
datos = np.genfromtxt("../data/estudiantes_notas_2.csv", delimiter=",", skip_header=1, usecols=(0, 1, 2, 3))

print("Datos cargados:\n", datos)
print("Forma de los datos:", datos.shape)

Datos cargados:
 [[  1.    38.08  70.12  19.33]
 [  2.    95.12  54.07  54.65]
 [  3.    73.47  31.64  87.42]
 ...
 [498.     8.7   14.55  46.89]
 [499.    97.47  95.07  38.6 ]
 [500.    98.63  45.15  86.47]]
Forma de los datos: (500, 4)


## Cambiar dimensiones: Experimentar con diferentes formas del arreglo.

In [5]:
#Cambiar dimensiones: Experimentar con diferentes formas del arreglo.
print ("El tipo de dato es:", type(datos)) # Usamos type()
print ("Primer elemento del array:", datos[0]) #Muestra elemento 1
print("Dimensión del array unidimensional:", datos.ndim)
print("Forma del array 2D:", datos.shape)
nuevo_array = datos.reshape(8,250) #si la forma orignal da 2000 elementos (500x4), las siguientes formas deben mantener ese numero de elementos
print ("Nuevo array:\n", nuevo_array)
print("Forma del Nuevo array:", nuevo_array.shape)

El tipo de dato es: <class 'numpy.ndarray'>
Primer elemento del array: [ 1.   38.08 70.12 19.33]
Dimensión del array unidimensional: 2
Forma del array 2D: (500, 4)
Nuevo array:
 [[  1.    38.08  70.12 ...  98.42  63.    83.05]
 [ 14.5   77.06  64.   ...  23.57  62.21  65.87]
 [126.    43.28  37.52 ...  69.1  188.    55.96]
 ...
 [ 13.34  55.21 314.   ...   8.05   3.51  25.48]
 [376.    32.58  16.46 ...  31.49 438.    82.36]
 [ 91.52  70.76 439.   ...  98.63  45.15  86.47]]
Forma del Nuevo array: (8, 250)


## Normalización: Comparar métodos de normalización (Min-Max y Z-Score).

In [6]:
min_val = np.min(datos)
print("min_val:",min_val)
max_val = np.max(datos)
print("max_val:",max_val)
array_minmax = (datos - min_val) / (max_val - min_val)
print("Arreglo Normalizado (Min-Max):", array_minmax)

min_val: 1.0
max_val: 500.0
Arreglo Normalizado (Min-Max): [[0.         0.07430862 0.13851703 0.03673347]
 [0.00200401 0.18861723 0.10635271 0.10751503]
 [0.00400802 0.14523046 0.06140281 0.17318637]
 ...
 [0.99599198 0.01543086 0.02715431 0.09196393]
 [0.99799599 0.19332665 0.18851703 0.0753507 ]
 [1.         0.1956513  0.08847695 0.17128257]]


In [7]:
# Z-Score Normalization 1D
media = np.mean(datos)
print("media:",media)
desviacion = np.std(datos)
print("desviacion:",desviacion)
array_zscore = (datos - media) / desviacion
print("Arreglo Normalizado (Z-Score) una dimensión:", array_zscore)

media: 100.45236
desviacion: 115.533898331314
Arreglo Normalizado (Z-Score) una dimensión: [[-0.86080675 -0.53986199 -0.26254078 -0.70215202]
 [-0.85215129 -0.04615407 -0.40146105 -0.39644088]
 [-0.84349582 -0.23354496 -0.5956032  -0.11280118]
 ...
 [ 3.44096101 -0.79415965 -0.74352516 -0.46360731]
 [ 3.44961648 -0.02581372 -0.04658685 -0.53536114]
 [ 3.45827195 -0.01577338 -0.47866783 -0.12102387]]


#### Segun lo leido, el min y max funciona bien cuando el rango de valores es cercano, pero si es tan alejado como de 1 a 500 puede generar una normalizacion con problemas con los outlier, que implique un minimo muy comprimido por decirlo de alguna manera. En cambio con Z-Score los resultados dados entregan mas resistencia a los valores fuera de la tendencia de los datos.

## Operaciones estadísticas: Calcular desviación estándar, promedios, etc.

In [8]:
# Suma de elementos
suma = np.sum(datos)
print("Suma de elementos:", suma)
print("Suma de elementos primera fila", np.sum(datos[0]))

# Raíz cuadrada de elementos
raiz_cuadrada = np.sqrt(datos)
print("raiz cuadrada de los elementos,",raiz_cuadrada)

raiz_cuadrada_redondeada = np.round(np.sqrt(datos),1) # Pueden probar anteponiendo np.round () para redondear decimales

print("Raíz cuadrada redondeada de elementos:\n", raiz_cuadrada_redondeada)

# Media de elementos
media = np.mean(datos)
print("Media de elementos:", media)

# Varianza de elementos
varianza = np.var(datos)
print("Varianza de elementos:", varianza)

# Mediana de elementos
mediana = np.median(datos)
print("Mediana de elementos:", mediana)

# Mediana elementos tercera fila
mediana_fila = np.median(datos[2])
print("Mediana de elementos tercera fila:", mediana_fila)

# Suma de primera fila matriz
suma_fila = np.sum(datos[0])
print("Suma de la primera fila:", suma_fila)

# Máximo elemento del array
maximo = np.max(datos)
print("Máximo elemento del array:", maximo)

# Minimo elemento del array
minimo = np.min(datos)
print("Mínimo elemento del array:", minimo)

# Máximo elemento de la primera fila del array
maximo_fila = np.max(datos[0])
print("Máximo elemento de la primera fila:", maximo_fila)

# sumar dos arrays
array_1 = np.array(datos[0])
array_2 = np.array(datos[1])
suma_arrays = array_1 + array_2
print("Suma de arrays ",array_1,"+",array_2,"=",suma_arrays)


# Multiplicación de arrays
array_1 = np.array(datos[2])
array_2 = np.array(datos[3])
multiplicacion_arrays = array_1 * array_2
print("Multiplicación de arrays", array_1 ,"*", array_2,"=", multiplicacion_arrays)

Suma de elementos: 200904.72
Suma de elementos primera fila 128.53
raiz cuadrada de los elementos, [[ 1.          6.17089945  8.37376857  4.39658959]
 [ 1.41421356  9.75294827  7.35323058  7.39256383]
 [ 1.73205081  8.57146429  5.62494444  9.34986631]
 ...
 [22.3159136   2.94957624  3.81444622  6.84762733]
 [22.3383079   9.8726896   9.75038461  6.21288983]
 [22.36067977  9.93126377  6.71937497  9.29892467]]
Raíz cuadrada redondeada de elementos:
 [[ 1.   6.2  8.4  4.4]
 [ 1.4  9.8  7.4  7.4]
 [ 1.7  8.6  5.6  9.3]
 ...
 [22.3  2.9  3.8  6.8]
 [22.3  9.9  9.8  6.2]
 [22.4  9.9  6.7  9.3]]
Media de elementos: 100.45236
Varianza de elementos: 13348.081663630403
Mediana de elementos: 63.394999999999996
Mediana de elementos tercera fila: 52.555
Suma de la primera fila: 128.53
Máximo elemento del array: 500.0
Mínimo elemento del array: 1.0
Máximo elemento de la primera fila: 70.12
Suma de arrays  [ 1.   38.08 70.12 19.33] + [ 2.   95.12 54.07 54.65] = [  3.   133.2  124.19  73.98]
Multiplica

## Filtro de datos: Filtrar estudiantes que cumplan ciertos criterios, como obtener más de 70 en Matemáticas.

In [4]:
filtro_matematicas = datos[:, 1] > 70  # Columna 0 es Matemáticas
print ("Filtro matemáticas", filtro_matematicas)
print("Estudiantes con nota en Matemáticas > 70:\n", datos[filtro_matematicas])

Filtro matemáticas [False  True  True False False False False  True False  True False  True
  True False False False False False False False False False False False
 False  True False False False False False False False  True  True  True
 False False False False False False False  True False False False False
 False False  True  True  True  True False  True False False False False
 False False  True False False False False  True False  True  True False
 False  True  True  True  True False False False  True False False False
 False False  True False  True False False  True  True False  True False
 False False False False False False False False  True False False  True
 False False False False  True  True False  True  True False  True False
  True  True False False False False  True  True False False False False
 False False  True False False  True False  True  True False False False
 False False False False False False  True False False False  True False
 False  True False  True False F