# DESAFIO
* Cargar el archivo estudiantes_notas en su entorno de trabajo.
* Cambiar dimensiones: Experimentar con diferentes formas del arreglo.
* Normalización: Comparar métodos de normalización (Min-Max y Z-Score).
* Operaciones estadísticas: Calcular desviación estándar, promedios, etc.
* Filtro de datos: Filtrar estudiantes que cumplan ciertos criterios, como obtener más de 70 en Matemáticas.

## Cargar el archivo estudiantes_notas en su entorno de trabajo.

In [16]:
import numpy as np

# Cargar los datos desde el archivo CSV (sin la columna 'Estudiante_ID')
datos = np.genfromtxt("../data/estudiantes_notas_2.csv", delimiter=",", skip_header=1, usecols=(0, 1, 2, 3))

print("Datos cargados:\n", datos)
print("Forma de los datos:", datos.shape)

Datos cargados:
 [[  1.    38.08  70.12  19.33]
 [  2.    95.12  54.07  54.65]
 [  3.    73.47  31.64  87.42]
 ...
 [498.     8.7   14.55  46.89]
 [499.    97.47  95.07  38.6 ]
 [500.    98.63  45.15  86.47]]
Forma de los datos: (500, 4)


## Cambiar dimensiones: Experimentar con diferentes formas del arreglo.

In [30]:
#Cambiar dimensiones: Experimentar con diferentes formas del arreglo.
print ("El tipo de dato es:", type(datos)) # Usamos type()
print ("Primer elemento del array:", datos[0]) #Muestra elemento 1
print("Dimensión del array unidimensional:", datos.ndim)
print("Forma del array 2D:", datos.shape)
nuevo_array = datos.reshape(8,250) #si la forma orignal da 2000 elementos (500x4), las siguientes formas deben mantener ese numero de elementos
print ("Nuevo array:\n", nuevo_array)
print("Forma del Nuevo array:", nuevo_array.shape)

El tipo de dato es: <class 'numpy.ndarray'>
Primer elemento del array: [ 1.   38.08 70.12 19.33]
Dimensión del array unidimensional: 2
Forma del array 2D: (500, 4)
Nuevo array:
 [[  1.    38.08  70.12 ...  98.42  63.    83.05]
 [ 14.5   77.06  64.   ...  23.57  62.21  65.87]
 [126.    43.28  37.52 ...  69.1  188.    55.96]
 ...
 [ 13.34  55.21 314.   ...   8.05   3.51  25.48]
 [376.    32.58  16.46 ...  31.49 438.    82.36]
 [ 91.52  70.76 439.   ...  98.63  45.15  86.47]]
Forma del Nuevo array: (8, 250)


## Normalización: Comparar métodos de normalización (Min-Max y Z-Score).